/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import super_interface.pilihKendaraanSuper;
import control.pilihMobilCtr;
import java.awt.event.KeyEvent;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import validasi.validasi;

/**
 *
 * @author Alif
 */
public class formPilihMobil extends javax.swing.JInternalFrame {

    private pilihKendaraanSuper pilihKndrn;
    
    validasi Valid = new validasi();

    /**
     * Creates new form formPilihMobil1
     */
    public formPilihMobil(String nama, String nik, String alamat, String tlp, String email) {
        initComponents();
        pilihKndrn = new pilihMobilCtr(this);
        pilihKndrn.tampilkan_data();
        pilihKndrn.nama = nama;
        pilihKndrn.nik = nik;
        pilihKndrn.alamat = alamat;
        pilihKndrn.tlp = tlp;
        pilihKndrn.email = email;
    }

    public JTable getTabelMobil() {
        return tabelMobil;
    }

    public JLabel getHarga() {
        return lbl_harga;
    }

    public JLabel getMerk() {
        return lbl_merk;
    }

    public JLabel getNopol() {
        return lbl_nopol;
    }

    public JLabel getStatus() {
        return lbl_status;
    }

    public JLabel getTahun() {
        return lbl_tahun;
    }

    public JLabel getTipe() {
        return lbl_tipe;
    }

    public JTextField getSearch() {
        return tfSearch;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btBerikutnya = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMobil = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_status = new javax.swing.JLabel();
        lbl_merk = new javax.swing.JLabel();
        lbl_tipe = new javax.swing.JLabel();
        lbl_tahun = new javax.swing.JLabel();
        lbl_nopol = new javax.swing.JLabel();
        lbl_harga = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        btSearch = new javax.swing.JButton();
        btKembali = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btBerikutnya.setBackground(new java.awt.Color(243, 179, 4));
        btBerikutnya.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btBerikutnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/next.png"))); // NOI18N
        btBerikutnya.setText("Berikutnya");
        btBerikutnya.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btBerikutnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBerikutnyaActionPerformed(evt);
            }
        });
        getContentPane().add(btBerikutnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 510, -1, -1));

        tabelMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMobilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMobil);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 830, 130));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel2.setText("PILIH MOBIL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(206, 228, 237));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setText("Status");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setText("Merk Mobil");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setText("Tipe Mobil");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setText("Tahun Produksi");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel6.setText("No. Polisi");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 30));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel8.setText("Harga Sewa/hari");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel7.setText(":");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel9.setText(":");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 10, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel10.setText(":");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 10, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel11.setText(":");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 10, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel12.setText(":");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 10, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel13.setText(":");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 10, -1));

        lbl_status.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_status.setText(" ");
        jPanel1.add(lbl_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        lbl_merk.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_merk.setText(" ");
        jPanel1.add(lbl_merk, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        lbl_tipe.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_tipe.setText(" ");
        jPanel1.add(lbl_tipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        lbl_tahun.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_tahun.setText(" ");
        jPanel1.add(lbl_tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        lbl_nopol.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_nopol.setText(" ");
        jPanel1.add(lbl_nopol, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, 30));

        lbl_harga.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_harga.setText(" ");
        jPanel1.add(lbl_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 830, 260));

        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });
        tfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSearchKeyPressed(evt);
            }
        });
        getContentPane().add(tfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 190, 30));

        btSearch.setBackground(new java.awt.Color(243, 179, 4));
        btSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        btSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, 50, 30));

        btKembali.setBackground(new java.awt.Color(243, 179, 4));
        btKembali.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        btKembali.setText("Kembali");
        btKembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 957, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btBerikutnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBerikutnyaActionPerformed
        pilihKndrn.berikutnya();
    }//GEN-LAST:event_btBerikutnyaActionPerformed

    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchActionPerformed

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        pilihKndrn.cari();
    }//GEN-LAST:event_btSearchActionPerformed

    private void tabelMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMobilMouseClicked
        pilihKndrn.klikTabel(evt);
    }//GEN-LAST:event_tabelMobilMouseClicked

    private void btKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKembaliActionPerformed
        pilihKndrn.kembali();
    }//GEN-LAST:event_btKembaliActionPerformed

    private void tfSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            btSearchActionPerformed(null);
        }else{
            Valid.pindah(evt, tfSearch, btSearch);
        }
    }//GEN-LAST:event_tfSearchKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btBerikutnya;
    private javax.swing.JButton btKembali;
    private javax.swing.JButton btSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_harga;
    private javax.swing.JLabel lbl_merk;
    private javax.swing.JLabel lbl_nopol;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JLabel lbl_tahun;
    private javax.swing.JLabel lbl_tipe;
    private javax.swing.JTable tabelMobil;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
