/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import control.isiDataCtr;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import super_interface.isiDataIntrfc;

/**
 *
 * @author Alif
 */
public class formIsiData extends javax.swing.JInternalFrame {

    private isiDataIntrfc isidata;

    /**
     * Creates new form formIsiData
     */
    public formIsiData() {
        initComponents();
        isidata = new isiDataCtr(this);
        isidata.kosongkan_form();
    }

    public JTextField getAlamat() {
        return tfAlamat;
    }

    public JTextField getEmail() {
        return tfEmail;
    }

    public JTextField getNIK() {
        return tfNIK;
    }

    public JTextField getNama() {
        return tfNama;
    }

    public JTextField getNotelp() {
        return tfNotelp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfNIK = new javax.swing.JTextField();
        tfAlamat = new javax.swing.JTextField();
        tfNotelp = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btPilihMobil = new javax.swing.JButton();
        btPilihMotor = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel2.setText("FORM PEMINJAMAN MOBIL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel3.setBackground(new java.awt.Color(206, 228, 237));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel13.setText("Nama");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel14.setText("NIK");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel15.setText("Alamat");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 30));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel16.setText("No. Telpon");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel17.setText("Email");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        tfNama.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tfNama.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });
        jPanel3.add(tfNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 340, 30));

        tfNIK.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tfNIK.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfNIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNIKActionPerformed(evt);
            }
        });
        jPanel3.add(tfNIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 340, 30));

        tfAlamat.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tfAlamat.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAlamatActionPerformed(evt);
            }
        });
        jPanel3.add(tfAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 340, 30));

        tfNotelp.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tfNotelp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfNotelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNotelpActionPerformed(evt);
            }
        });
        jPanel3.add(tfNotelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 340, 30));

        tfEmail.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tfEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });
        jPanel3.add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 340, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ilustrasi1.png"))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel19.setText("Email");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 830, 420));

        btPilihMobil.setBackground(new java.awt.Color(243, 179, 4));
        btPilihMobil.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btPilihMobil.setText("Pilih Mobil");
        btPilihMobil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPilihMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPilihMobilActionPerformed(evt);
            }
        });
        getContentPane().add(btPilihMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, -1, -1));

        btPilihMotor.setBackground(new java.awt.Color(243, 179, 4));
        btPilihMotor.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btPilihMotor.setText("Pilih Motor");
        btPilihMotor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPilihMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPilihMotorActionPerformed(evt);
            }
        });
        getContentPane().add(btPilihMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 957, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaActionPerformed

    private void tfNIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNIKActionPerformed

    private void tfAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAlamatActionPerformed

    private void tfNotelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNotelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNotelpActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void btPilihMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPilihMobilActionPerformed
        isidata.pilihMobil();
    }//GEN-LAST:event_btPilihMobilActionPerformed

    private void btPilihMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPilihMotorActionPerformed
        isidata.pilihMotor();
    }//GEN-LAST:event_btPilihMotorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btPilihMobil;
    private javax.swing.JButton btPilihMotor;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNIK;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNotelp;
    // End of variables declaration//GEN-END:variables
}
