/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import control.pengembalianCtr;
import java.awt.event.KeyEvent;
import javax.swing.JLabel;
import javax.swing.JTextField;
import validasi.validasi;
import super_interface.pengembalianIntrfc;

/**
 *
 * @author Alif
 */
public class formPengembalian extends javax.swing.JInternalFrame {

    private pengembalianIntrfc pbln;
    
    validasi Valid = new validasi();

    /**
     * Creates new form formPengembalian1
     */
    public formPengembalian() {
        initComponents();
        pbln = new pengembalianCtr(this);
        pbln.tampilankosong();
    }

    public JLabel getHarga() {
        return lbl_harga;
    }

    public JLabel getKendaraan() {
        return lbl_kendaraan;
    }

    public JLabel getLama() {
        return lbl_lama;
    }

    public JLabel getNik() {
        return lbl_nik;
    }

    public JLabel getNopol() {
        return lbl_nopol;
    }

    public JLabel getTglkembali() {
        return lbl_tglkembali;
    }

    public JLabel getTglpinjam() {
        return lbl_tglpinjam;
    }

    public JLabel getTipe() {
        return lbl_tipe;
    }

    public JLabel getTotal() {
        return lbl_total;
    }

    public JTextField getNama() {
        return tfNama;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_nik = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbl_tglpinjam = new javax.swing.JLabel();
        lbl_tipe = new javax.swing.JLabel();
        lbl_nopol = new javax.swing.JLabel();
        lbl_harga = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbl_tglkembali = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_lama = new javax.swing.JLabel();
        btKembalikan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        btSearch = new javax.swing.JButton();
        lbl_kendaraan = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel2.setText("FORM PENGEMBALIAN MOBIL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(206, 228, 237));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setText("NIK");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        lbl_nik.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_nik.setText("lbl_nik");
        jPanel1.add(lbl_nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setText("Tanggal Peminjaman");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel14.setText("Tipe Mobil");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel16.setText("No. Polisi");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 30));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel17.setText("Harga Sewa/hari");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel19.setText(":");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 10, -1));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel20.setText(":");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 10, -1));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel22.setText(":");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 10, -1));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel23.setText(":");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 10, -1));

        lbl_tglpinjam.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_tglpinjam.setText("lbl_tglpinjam");
        jPanel1.add(lbl_tglpinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        lbl_tipe.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_tipe.setText("lbl_tipe");
        jPanel1.add(lbl_tipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        lbl_nopol.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_nopol.setText("lbl_nopol");
        jPanel1.add(lbl_nopol, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, 30));

        lbl_harga.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_harga.setText("lbl_harga");
        jPanel1.add(lbl_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel24.setText(":");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel25.setText(":");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 10, -1));

        tfNama.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tfNama.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });
        tfNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNamaKeyPressed(evt);
            }
        });
        jPanel1.add(tfNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 340, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setText("Tanggal Pengembalian");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel21.setText(":");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 10, -1));

        lbl_tglkembali.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_tglkembali.setText("lbl_tglkembali");
        jPanel1.add(lbl_tglkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel26.setText(":");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 10, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel6.setText("Lama Peminjaman");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        lbl_lama.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_lama.setText("lbl_lama");
        jPanel1.add(lbl_lama, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        btKembalikan.setBackground(new java.awt.Color(243, 179, 4));
        btKembalikan.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btKembalikan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/car4.png"))); // NOI18N
        btKembalikan.setText("Kembalikan");
        btKembalikan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btKembalikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKembalikanActionPerformed(evt);
            }
        });
        jPanel1.add(btKembalikan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel7.setText("Total Biaya Peminjaman");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel27.setText(":");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 10, -1));

        lbl_total.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_total.setText("lbl_total");
        jPanel1.add(lbl_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        btSearch.setBackground(new java.awt.Color(243, 179, 4));
        btSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        btSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 50, 30));

        lbl_kendaraan.setBackground(new java.awt.Color(206, 228, 237));
        lbl_kendaraan.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_kendaraan.setForeground(new java.awt.Color(206, 228, 237));
        lbl_kendaraan.setText("kendaraan");
        jPanel1.add(lbl_kendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 830, 470));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 957, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaActionPerformed
        
    }//GEN-LAST:event_tfNamaActionPerformed

    private void btKembalikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKembalikanActionPerformed
        pbln.kembalikan();
    }//GEN-LAST:event_btKembalikanActionPerformed

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        pbln.cari();
    }//GEN-LAST:event_btSearchActionPerformed

    private void tfNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNamaKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            btSearchActionPerformed(null);
        }else{
            Valid.pindah(evt, tfNama, btSearch);
        }
    }//GEN-LAST:event_tfNamaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btKembalikan;
    private javax.swing.JButton btSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_harga;
    private javax.swing.JLabel lbl_kendaraan;
    private javax.swing.JLabel lbl_lama;
    private javax.swing.JLabel lbl_nik;
    private javax.swing.JLabel lbl_nopol;
    private javax.swing.JLabel lbl_tglkembali;
    private javax.swing.JLabel lbl_tglpinjam;
    private javax.swing.JLabel lbl_tipe;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTextField tfNama;
    // End of variables declaration//GEN-END:variables
}
