/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author Alif
 */
public class menuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form menuAdmin
     */
    public menuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btMobil = new javax.swing.JButton();
        btMotor = new javax.swing.JButton();
        btPenyewa = new javax.swing.JButton();
        btLogout = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 50));
        setPreferredSize(new java.awt.Dimension(1190, 660));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setText("MENU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setText("ADMIN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        btMobil.setBackground(new java.awt.Color(243, 179, 4));
        btMobil.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btMobil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/car1.png"))); // NOI18N
        btMobil.setText("Mobil");
        btMobil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMobilActionPerformed(evt);
            }
        });
        getContentPane().add(btMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, 60));

        btMotor.setBackground(new java.awt.Color(243, 179, 4));
        btMotor.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btMotor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/motor.png"))); // NOI18N
        btMotor.setText("Motor");
        btMotor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMotorActionPerformed(evt);
            }
        });
        getContentPane().add(btMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 180, 60));

        btPenyewa.setBackground(new java.awt.Color(243, 179, 4));
        btPenyewa.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btPenyewa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/people.png"))); // NOI18N
        btPenyewa.setText("Penyewa");
        btPenyewa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPenyewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPenyewaActionPerformed(evt);
            }
        });
        getContentPane().add(btPenyewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 180, 60));

        btLogout.setBackground(new java.awt.Color(255, 51, 51));
        btLogout.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        btLogout.setText("Logout");
        btLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, -1));
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 970, 620));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg2.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 957, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPenyewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPenyewaActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        dataPenyewa dp = new dataPenyewa();
        dp.setVisible(true);
        jDesktopPane1.add(dp);
    }//GEN-LAST:event_btPenyewaActionPerformed

    private void btMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMobilActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        formTambahMobil tm = new formTambahMobil();
        tm.setVisible(true);
        jDesktopPane1.add(tm);    }//GEN-LAST:event_btMobilActionPerformed

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        this.dispose();
        login l = new login();
        l.setVisible(true);
    }//GEN-LAST:event_btLogoutActionPerformed

    private void btMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMotorActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        formTambahMotor mtr = new formTambahMotor();
        mtr.setVisible(true);
        jDesktopPane1.add(mtr);
    }//GEN-LAST:event_btMotorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btMobil;
    private javax.swing.JButton btMotor;
    private javax.swing.JButton btPenyewa;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
